version: '2'

########################### networks
networks:
  grafana-nw:
  traefik-proxy:
    external: true
########################### SERVICES
services:
  influxdb:
    restart: always
    image: influxdb:1.8
    ports:
      - "8886:8086"
    volumes:
      - "./docker-speedtest-grafana/data/influxdb/:/var/lib/influxdb"
    environment:
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=password"
      - "INFLUXDB_DB=speedtest"
    networks:
      - grafana-nw
  grafana:
    restart: always
    container_name: grafana
    image: grafana/grafana:6.7.2
    volumes:
      - "./docker-speedtest-grafana/grafana/provisioning:/etc/grafana/provisioning"
    ports:
      - 3000
    environment:
      - "GF_SERVER_ROOT_URL=http://localhost"
      - "GF_SECURITY_ADMIN_PASSWORD=admin"
      - "GF_AUTH_ANONYMOUS_ENABLED=true"
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - traefik-proxy
      - grafana-nw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      - "traefik.http.routers.grafana.rule=Host(`grafana.$DOMAINNAME`)"
      - "traefik.http.routers.grafana.middlewares=traefik-https-redirect"
      - "traefik.http.routers.grafana-secure.entrypoints=https"
      - "traefik.http.routers.grafana-secure.rule=Host(`grafana.$DOMAINNAME`)"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.grafana-secure.service=grafana"     
  speedtest:
    restart: always
    container_name: speedtest
    image: frdmn/speedtest-grafana:latest
    container_name: speedtest
    environment:
      - "SPEEDTEST_INTERVAL=1000"
      - "SPEEDTEST_HOST=local"
    depends_on:
      - influxdb
    networks:
      - grafana-nw

