version: "3"

########################### networks
networks:
  traefik-proxy:
    external: true
########################### SERVICES
services:
  giteaserver:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=$USER_UID
      - USER_GID=$USER_GID
      - DISABLE_REGISTRATION="true"
    restart: always
    networks:
    #  - gitea
      - traefik-proxy
    volumes:
      - ./gitea:/data
      - /home/git/.ssh/:/data/git/.ssh
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      #- 3000:3000
      - "2222:22"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.http.routers.gitea.entrypoints=http"
      - "traefik.http.routers.gitea.rule=Host(`gitea.$DOMAINNAME`)"
      - "traefik.http.routers.gitea.middlewares=traefik-https-redirect"
      - "traefik.http.routers.gitea-secure.entrypoints=https"
      - "traefik.http.routers.gitea-secure.rule=Host(`gitea.$DOMAINNAME`)"
      - "traefik.http.routers.gitea-secure.tls=true"
      - "traefik.http.routers.gitea-secure.tls.certresolver=letsEncryptDNS"
      - "traefik.http.routers.gitea-secure.service=gitea" #follows container name
      
