version: '3.8'
########################### networks
networks:
  traefik-proxy:
    external: true
########################### SERVICES
services:
  wgeasy:
    image: weejewel/wg-easy
    container_name: wgeasy
    volumes:
      - ./wireguard:/etc/wireguard
    ports:
      #- "51820:51820/udp"
      #- "51821:51821/tcp"
      - 443:51820/udp
      - 443:51821/tcp
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      # ⚠️ Required:
      # Change this to your host's public address
      - WG_HOST=129.146.250.58
      # Optional:
      # - PASSWORD=foobar123
      # - WG_PORT=51820
      # - WG_DEFAULT_ADDRESS=10.8.0.x
      # - WG_DEFAULT_DNS=1.1.1.1
      # - WG_MTU=1420
      # - WG_ALLOWED_IPS=192.168.15.0/24, 10.0.1.0/24
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wgeasy.entrypoints=http"
      - "traefik.http.routers.wgeasy.rule=Host(`wgeasy.$DOMAINNAME`)"
      - "traefik.http.routers.wgeasy.middlewares=traefik-https-redirect"
      - "traefik.http.routers.wgeasy-secure.entrypoints=https"
      - "traefik.http.routers.wgeasy-secure.rule=Host(`wgeasy.$DOMAINNAME`)"
      - "traefik.http.routers.wgeasy-secure.tls=true"
      - "traefik.http.routers.wgeasy-secure.tls.certresolver=letsEncryptDNS"
      - "traefik.http.routers.wgeasy-secure.service=wgeasy"     
     
